import { PHYSICS_CONFIG } from './physics';

export const PARTICLE_CONFIG = {
  EXPLOSION_LIFETIME_MIN: 1.5,
  EXPLOSION_LIFETIME_MAX: 2.0,
  FOUNTAIN_LIFETIME_MIN: 1.2,
  FOUNTAIN_LIFETIME_MAX: 2.0,
} as const;

export const EXPLOSION_CONFIG = {
  PARTICLE_COUNT_MIN: 30,
  PARTICLE_COUNT_MAX: 50,
  SPEED_MIN: 150,
  SPEED_MAX: 300,
  GRAVITY:
    PHYSICS_CONFIG.BASE_GRAVITY * PHYSICS_CONFIG.EXPLOSION_GRAVITY_MULTIPLIER,
} as const;

export const FOUNTAIN_CONFIG = {
  PARTICLES_PER_FRAME: 3,
  SPEED_MIN: 120,
  SPEED_MAX: 200,
  GRAVITY:
    PHYSICS_CONFIG.BASE_GRAVITY * PHYSICS_CONFIG.FOUNTAIN_GRAVITY_MULTIPLIER,
  CONE_ANGLE: Math.PI / 6,
  SPAWN_RADIUS: 20,
} as const;

export const MAX_PARTICLE_LIFETIME =
  Math.max(
    PARTICLE_CONFIG.EXPLOSION_LIFETIME_MAX,
    PARTICLE_CONFIG.FOUNTAIN_LIFETIME_MAX,
  ) * 1000;
